### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by TawalMc** [nioperas06/bj-decoupage-territorial#6]
Good morning nioperas06. 
Bonjour nioperas06.
Suis béninois étudiant en 4ème année de génie énergétique et procédés et adepte de la programmation informatique: C++; Javascript(React/Nodejs). J'ai vu ce dépot et j'ai apprécié grave. Vous aviez fait un travail de génie en mettant en place cette api. J'aimerais bien contribuer d'une quelconque manière. En fait je viens de mettre au point une petite appli web de type jeu (QCM sur les départements et communes du Bénin) basée sur React et hébergée sur Heroku. Vous pouvez la consulter  [via ce lien](https://departements.herokuapp.com/) . Je ne savais pas qu'il y avait une api qui fournisait des infos sur le découpage territoriale au Bénin. J'ai juste utilisé les départements et leurs communes. Vous pouvez jeter un coup d'oeil au [dépot ici](https://github.com/TawalMc/departements_Benin.git)

**Comment by nioperas06** [comment]
Merci
